#!/bin/sh

#  Figure out where we're being called from
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

PROJ_DIR="$1"
PATH_SEP="/"
QUOTE="\""
FILE="StringsFileParser.swift"
BACK="/.."
BUILD="Build/Products/Debug/Build"
LOCALIZABLE_STRINGS=$( mdfind -onlyin $PROJ_DIR Localizable.strings )


eval $PROJ_DIR$BACK$PATH_SEP$BUILD $PROJ_DIR $LOCALIZABLE_STRINGS
