#!/bin/sh

#  Figure out where we're being called from
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#  Quote path in case of spaces or special chars
#DIR="\"${DIR}"

PROJ_DIR="$1"
PATH_SEP="/"
QUOTE="\""
FILE="StringsFileParser.swift"
BACK="/.."
BUILD="Build/Products/Debug/Build"
LOCALIZABLE_STRINGS=$( mdfind -onlyin $PROJ_DIR Localizable.strings )

#echo $DIR
#echo $PROJ_DIR

eval $PROJ_DIR$BACK$PATH_SEP$BUILD $PROJ_DIR $LOCALIZABLE_STRINGS

# project_folder="$1"
# if [ "$1" != "" ]; then
#     echo "Files project folder: $project_folder"
# else
#     echo "Project name not provided stopped process"
#     exit 1
# fi
# ​
# mkdir -p "$project_folder/Resources/SwiftGen"
# ​
# swiftgen storyboards "$project_folder" --output "$project_folder/Resources/SwiftGen/Storyboards.swift"
# swiftgen images "$project_folder" --output "$project_folder/Resources/SwiftGen/Images.swift"
# swiftgen colors "$project_folder/Resources/Colors.rgb" --output "$project_folder/Resources/SwiftGen/Colors.swift"
# swiftgen strings "$project_folder/Resources/en.lproj/Localizable.strings" --templatePath "$project_folder/Resources/SwiftGen/strings-template.stencil" --output "$project_folder/Resources/SwiftGen/Strings.swift"
