source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Localizable_Example', :exclusive => true do
  pod 'Localizable', :path => '../'
end

target 'Localizable_Tests', :exclusive => true do
  pod 'Localizable', :path => '../'

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
end

# Hack to fix testability until cocoapods gets an update
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == 'Debug'
        config.build_settings['ENABLE_TESTABILITY'] = 'YES'
      end
    end
  end
end